# Generated by Django 3.2.3 on 2021-06-07 12:32

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('allowed_list', blog.models.ListField(token=',')),
            ],
        ),
    ]
