# Generated by Django 3.2.3 on 2021-06-11 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='taget-post')),
            ],
        ),
    ]
